language: php
services:
  - mysql
php:
  - 7.1
mysql:
  database: drupal
  username: root
  encoding: utf8

cache:
  directories:
     - $HOME/.composer/cache
     - $HOME/.drush/cache

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:8.1.* torotil/upal:1.1.3 phpunit/phpunit:6.4.*

before_script:
  - repo=`pwd`
  - root=$HOME/test-root
  - mysql -e 'create database drupal'
  - php -d include_path=`pwd` -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --core=drupal-7.60 --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/drupal --root=$root
  - cd $root
  - ln -s $repo sites/all/modules/module_under_test
  - drush dl entity campaignion payment payment_context payment_controller_data payment_forms psr0
  - drush --yes pm-enable sagepay_payment_test
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do sleep 0.1s; done

script:
  - cd $repo
  - UPAL_ROOT=$root UPAL_WEB_URL=http://127.0.0.1:8080 phpunit --bootstrap=$HOME/.composer/vendor/torotil/upal/bootstrap.php --coverage-clover=coverage.xml .

after_success:
  - bash <(curl -s https://codecov.io/bash)
